### PR TITLE
Invisible ReCaptcha

### PR DESCRIPTION
**Pull request by alexkazik**
Add support for Invisible ReCaptcha, as discussed in #3.

### CODE REVIEW

**Comment by ncaq** [comment]
I am sorry I have kept you waiting.

Would you kindly check **Allow edits from maintainers**.
[Allowing changes to a pull request branch created from a fork - User Documentation](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/)

I want commit of example style reformat.

**Comment by ncaq** [comment]
Well, I can commit after I merge,
Because you modify your code,
I think that this one is smoother.

**Comment by alexkazik** [comment]
I would go for 120 chars, but why is that now part of my pull, it seems not related.
But I don't mind.

**Comment by ncaq** [comment]
I do not mind over 100 char.
But I mind 120 char.
Because My Emacs width is about 100 char.

**Pull request merged**
